apiVersion: 1

datasources:
  - uid: grafanacloud-profiles-local
    type: grafana-pyroscope-datasource
    name: Local Pyroscope
    url: http://host.docker.internal:4040
    isDefault: true
    jsonData:
      keepCookies: [pyroscope_git_session]
    basicAuth: true
    # 1. our plugin backend expects a string
    # 2. this value must match the one in samples/provisioning/plugins/app.yaml
    basicAuthUser: '42'
    secureJsonData:
      basicAuthPassword: 'mypassword'
