name: Plugins - CI / CD

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  cd:
    name: CI / CD
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@ci-cd-workflows/v3.2.0
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      # Checkout/build PR or main branch, depending on event
      branch: ${{ github.event_name == 'push' && github.ref_name || github.ref }}

      # When pushing to "main", publish and deploy to Grafana Cloud (CD).
      # For PRs, skip publishing and deploying (run CI only).
      environment: ${{ (github.event_name == 'push' && github.ref_name == 'main') && 'dev' || 'none' }}

      scopes: universal

      # Argo CD inputs
      grafana-cloud-deployment-type: provisioned
      argo-workflow-slack-channel: "#grafana-plugins-platform-ci"
      auto-merge-environments: dev

      # Add the git head ref sha to the plugin version as suffix (`+abcdef`). This is required for CD builds.
      plugin-version-suffix: ${{ github.event_name == 'push' && github.sha || github.event.pull_request.head.sha }}

      # Other CI inputs
      run-playwright: true
      upload-playwright-artifacts: true
      node-version: 22
