name: Run Release Tests

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      # This exists bc if you destroy all things managed by Terraform and then re-create them... 
      # the project ID will change. This step fetches the right projectID based on the project name.
      - name: Fetch "backend" projectID
        env:
          GRAFANA_API_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          GRAFANA_STACK_ID: ${{ secrets.GRAFANA_STACK_ID }}
        run: |
          ./tools/fetch_gck6_projectID.sh backend

      - name: Set up k6
        uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2 # v1

      - name: Run backend tests
        id: run_k6
        uses: grafana/run-k6-action@a15e2072ede004e8d46141e33d7f7dad8ad08d9d # v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ env.K6_CLOUD_PROJECT_ID }}
        with:
          path: |
            ./src/backend/*.ts
          flags: --vus 100 --duration 60s
          parallel: true
          fail-fast: false
          cloud-run-locally: false

      - name: Annotate test runs with GitHub metadata
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          GRAFANA_STACK_ID: ${{ secrets.GRAFANA_STACK_ID }}
          K6_TEST_RUN_IDS: ${{ steps.run_k6.outputs.testRunIds }}
          GIT_BRANCH: ${{ github.ref_name }}
          RELEASE_NAME: ${{ github.event.release.name }}
        run: ./tools/set_gck6_note.sh


      - name: Set test runs as baseline
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_TEST_RUN_IDS: ${{ steps.run_k6.outputs.testRunIds }}
        run: ./tools/set_gck6_baseline.sh

