---
name: Test Helm Test

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths: [tools/helm-test/**]
  pull_request:
    paths: [tools/helm-test/**]
  workflow_dispatch:

permissions: {}

jobs:
  list-tests:
    name: List tests
    runs-on: ubuntu-latest
    outputs:
      localTests: ${{ steps.list_tests.outputs.localTests }}
      cloudTests: ${{ steps.list_tests.outputs.cloudTests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1
        with:
          persist-credentials: 'false'

      - name: List tests
        id: list_tests
        working-directory: tools/helm-test/tests
        run: |
          localTests=()
          cloudTests=()
          for testPlan in */test-plan.yaml; do
            clusterType="$(yq '.cluster.type' "${testPlan}")"
            if [[ "${clusterType}" == "kind" ]] || [[ "${clusterType}" == "minikube" ]]; then
              localTests+=("$(dirname "${testPlan}")")
            else
              cloudTests+=("$(dirname "${testPlan}")")
            fi
          done
          echo "localTests=$(printf '%s\n' "${localTests[@]}" | jq --raw-input | jq --slurp --compact-output)" >> "${GITHUB_OUTPUT}"
          echo "cloudTests=$(printf '%s\n' "${cloudTests[@]}" | jq --raw-input | jq --slurp --compact-output)" >> "${GITHUB_OUTPUT}"

  run-integration-tests:
    name: Integration Test
    needs: list-tests
    runs-on: ubuntu-latest
    if: needs.list-tests.outputs.localTests != '[]'
    strategy:
      matrix:
        test: ${{ fromJson(needs.list-tests.outputs.localTests) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1
        with:
          persist-credentials: 'false'
          path: source

      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1
        with:
          persist-credentials: 'false'
          repository: grafana/helm-chart-toolbox
          path: helm-chart-toolbox

      - name: Install Flux CLI
        uses: fluxcd/flux2/action@b6e76ca2534f76dcb8dd94fb057cdfa923c3b641  # v2.7.3

      - name: Install Kind CLI
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab  # v1.13.0
        with:
          install_only: true

      - name: Install Minikube CLI
        uses: medyagh/setup-minikube@e3c7f79eb1e997eabccc536a6cf318a2b0fe19d9  # v0.0.20
        with:
          start: false

      - name: Run test
        run: helm-chart-toolbox/tools/helm-test/helm-test "${TEST_DIRECTORY}"
        env:
          TEST_DIRECTORY: "source/tools/helm-test/tests/${{ matrix.test }}"
          DELETE_CLUSTER: true
