services:
  grafana:
    user: root
    container_name: 'grafana-pathfinder-app'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.3.0-19020365962}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/grafana-pathfinder-app
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/grafana-pathfinder-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.grafana-pathfinder-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-pathfinder-app
