apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xinstallations.k6.grafana.net.namespaced
  name: installation-namespaced
spec:
  compositeTypeRef:
    apiVersion: k6.grafana.net.namespaced/v1alpha1
    kind: XInstallation
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: k6.grafana.crossplane.io/v1alpha1
              kind: Installation
            name: installation
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.selectorLabel
                toFieldPath: "metadata.labels[\"selector\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.cloudAccessPolicyTokenSecretRef.key
                toFieldPath: spec.forProvider.cloudAccessPolicyTokenSecretRef.key
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.cloudAccessPolicyTokenSecretRef.name
                toFieldPath: spec.forProvider.cloudAccessPolicyTokenSecretRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.cloudAccessPolicyTokenSecretRef.namespace
                toFieldPath: spec.forProvider.cloudAccessPolicyTokenSecretRef.namespace
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.grafanaSaTokenSecretRef.key
                toFieldPath: spec.forProvider.grafanaSaTokenSecretRef.key
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.grafanaSaTokenSecretRef.name
                toFieldPath: spec.forProvider.grafanaSaTokenSecretRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.grafanaSaTokenSecretRef.namespace
                toFieldPath: spec.forProvider.grafanaSaTokenSecretRef.namespace
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.grafanaUser
                toFieldPath: spec.forProvider.grafanaUser
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.stackId
                toFieldPath: spec.forProvider.stackId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.cloudAccessPolicyTokenSecretRef.key
                toFieldPath: spec.initProvider.cloudAccessPolicyTokenSecretRef.key
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.cloudAccessPolicyTokenSecretRef.name
                toFieldPath: spec.initProvider.cloudAccessPolicyTokenSecretRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.cloudAccessPolicyTokenSecretRef.namespace
                toFieldPath: spec.initProvider.cloudAccessPolicyTokenSecretRef.namespace
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.grafanaSaTokenSecretRef.key
                toFieldPath: spec.initProvider.grafanaSaTokenSecretRef.key
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.grafanaSaTokenSecretRef.name
                toFieldPath: spec.initProvider.grafanaSaTokenSecretRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.grafanaSaTokenSecretRef.namespace
                toFieldPath: spec.initProvider.grafanaSaTokenSecretRef.namespace
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.grafanaUser
                toFieldPath: spec.initProvider.grafanaUser
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.stackId
                toFieldPath: spec.initProvider.stackId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
                toFieldPath: spec.publishConnectionDetailsTo.configRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
                toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
                toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
                toFieldPath: spec.publishConnectionDetailsTo.metadata.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
                toFieldPath: spec.publishConnectionDetailsTo.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform