apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xintegrations.oncall.grafana.net.namespaced
  name: integration-namespaced
spec:
  compositeTypeRef:
    apiVersion: oncall.grafana.net.namespaced/v1alpha1
    kind: XIntegration
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: oncall.grafana.crossplane.io/v1alpha1
              kind: Integration
            name: integration
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.selectorLabel
                toFieldPath: "metadata.labels[\"selector\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.defaultRoute
                toFieldPath: spec.forProvider.defaultRoute
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.dynamicLabels
                toFieldPath: spec.forProvider.dynamicLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.labels
                toFieldPath: spec.forProvider.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.name
                toFieldPath: spec.forProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.teamId
                toFieldPath: spec.forProvider.teamId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.templates
                toFieldPath: spec.forProvider.templates
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.type
                toFieldPath: spec.forProvider.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.defaultRoute
                toFieldPath: spec.initProvider.defaultRoute
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.dynamicLabels
                toFieldPath: spec.initProvider.dynamicLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.labels
                toFieldPath: spec.initProvider.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.name
                toFieldPath: spec.initProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.teamId
                toFieldPath: spec.initProvider.teamId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.templates
                toFieldPath: spec.initProvider.templates
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.type
                toFieldPath: spec.initProvider.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
                toFieldPath: spec.publishConnectionDetailsTo.configRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
                toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
                toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
                toFieldPath: spec.publishConnectionDetailsTo.metadata.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
                toFieldPath: spec.publishConnectionDetailsTo.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform