apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: collector-configurator
  title: collector-configurator
  description: |
    The Collector Configuration Generator is an easy to use web interface for creating and editing OpenTelemetry Collector configuration files.
  links:
    - title: Slack Channel
      url: https://raintank-corp.slack.com/archives/C034H8U2L81
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: grafana/collector-configurator
spec:
  type: website
  owner: group:default/devex
  lifecycle: production
