[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
]
all-features = true

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
exceptions = [
  { allow = ["GPL-3.0"], crate = "ministrace" }, # that's us!
]
