name: Merge pull request

on:
  repository_dispatch:
    types: [merge-pr]

permissions:
  contents: write
  pull-requests: write

jobs:
  Merge_pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Resolve possible conflicts with main
      env:
        RELEASE_BRANCH_NAME: ${{ github.event.client_payload.ReleaseBranchName }}
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Actions service account"
        git checkout "${RELEASE_BRANCH_NAME}-docs"
        git merge --no-edit --strategy-option=ours main
        git push origin "${RELEASE_BRANCH_NAME}-docs"
        sleep 30

    - name: Approve pull request by GitHub-Actions bot
      uses: actions/github-script@v8
      env:
        PR_NUMBER: ${{ github.event.client_payload.PullRequestNumber }}
      with:
        github-token: ${{secrets.PRAPPROVAL_SECRET}}
        script: |
          github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: Number(process.env.PR_NUMBER),
            event: "APPROVE"
          });

    - name: Merge pull request
      uses: actions/github-script@v8
      env:
        PR_NUMBER: ${{ github.event.client_payload.PullRequestNumber }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: Number(process.env.PR_NUMBER),
            merge_method: "squash"
          })
