name: Publish to plugin catalog

# Version Tag Publishing Process (TODO: Automate this process more):
# 1. Create your feature branch and make changes
# 2. Get your feature PR approved
# 3. Create a separate version bump PR:
#    - git switch -c bump-version-vX.Y.Z
#    - update CHANGELOG.md with a link to the forthcoming tag's release notes
#    - npm version <type>  # this creates the commit and tag (see https://docs.npmjs.com/cli/commands/npm-version for <type> options, e.g. patch, minor, major, prerelease, etc.)
#    - git push origin bump-version-vX.Y.Z --follow-tags
# 4. Get version bump PR approved
# 5. Merge feature PR first
# 6. Merge version bump PR
# The workflow will trigger when the version tag lands on main via the merge

on:
  workflow_dispatch:
    inputs:
      skip-grafana-dev-image:
        description: 'Bypass grafana-dev image for e2e tests'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main

permissions:
  contents: 'write'
  id-token: 'write'
  attestations: 'write'

jobs:
  CD:
    name: Deploy plugin
    # Don't run on forks, ensure tag is on main branch, and restrict workflow_dispatch to main/tag branches
    if: |
      github.repository == 'grafana/metrics-drilldown' &&
      (
        (github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'npm version')) ||
        (github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')))
      )
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@ci-cd-workflows/v4.2.0
    with:
      environment: 'prod' # publishing to 'prod' will also deploy to 'ops' and 'dev'
      attestation: true # this guarantees that the plugin was built from the source code provided in the release
      run-playwright: false
      run-playwright-docker: true
      upload-playwright-artifacts: true # IMPORTANT: we must ensure there are no unmasked secrets in the E2E tests
      run-playwright-with-skip-grafana-dev-image: ${{ inputs.skip-grafana-dev-image || false }}
      playwright-report-path: e2e/test-reports/
      playwright-docker-compose-file: docker-compose.yaml
      playwright-grafana-url: http://localhost:3001
      argo-workflow-slack-channel: '#proj-metricsdrilldown-cd'
