apiVersion: v2
name: grafana-cloud-onboarding
description: A Helm chart for Grafana Cloud Onboarding on Kubernetes
type: application
version: 0.4.0
appVersion: 1.16.0
dependencies:
  - name: alloy-operator
    version: 0.3.13
    repository: https://grafana.github.io/helm-charts
    condition: alloy-operator.enabled
  - name: beyla
    version: 1.10.0
    repository: https://grafana.github.io/helm-charts
  - name: kube-state-metrics
    version: 6.4.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: prometheus-node-exporter
    version: 4.49.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-node-exporter.enabled
  - name: prometheus-windows-exporter
    version: 0.12.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-windows-exporter.enabled
  - name: kepler
    version: 0.6.1
    repository: https://sustainable-computing-io.github.io/kepler-helm-chart
    condition: kepler.enabled
