apiVersion: 1

datasources:
  - name: 'âŒ yugabyte (default)'
    uid: yugabyte-default
    type: grafana-yugabyte-datasource
  - name: 'âœ… yugabyte (valid)'
    uid: yugabyte
    type: grafana-yugabyte-datasource
    isDefault: true
    url: yugabyte:5433
    user: yugabyte
    jsonData:
      database: yugabyte
    secureJsonData:
      password: yugabyte
