services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-11.3.0}
    ports:
      - 3000:3000/tcp
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
