---
remote: origin
target-branch: main
chart-dirs:
  - charts
excluded-charts:
  - alloy-crd
  - alloy-helm-chart
  - sample-parent-chart
chart-repos:
  - grafana=https://grafana.github.io/helm-charts
check-version-increment: false
validate-maintainers: true
