name: Validate renovate config
description: Run renovate-config-validator against a config file, or the default.

inputs:
  config:
    required: false
    default: ""
    description: |-
      Space-separated list of configs to validate. If empty (recommended), renovate will find the config for you.
  renovate-version:
    description: >-
      Renovate version to use (image tag).
      Leave empty to use the version specified in this repo, which is updated in sync with that of the renovate action.
      Alternatively, specify it and include the `renovate-version.json5` preset to have it updated.
    required: false
    # Renovate updates the line below. Please keep its formatting as it is.
    default: 42.11.0@sha256:c6950364d634f956a88238f46510f6a9a77809f3d4427c68110b7bd750afc759 # renovate-version

runs:
  using: composite
  steps:
    - name: Renovate config validator
      shell: bash
      env:
        INPUTS_CONFIG: ${{ inputs.config }}
        RENOVATE_IMAGE: ghcr.io/renovatebot/renovate:${{ inputs.renovate-version }}
      run: |

        if [[ -z "${INPUTS_CONFIG}" ]]; then
          docker run -i --rm -v "$(realpath .):/repo" -w /repo --entrypoint renovate-config-validator "${RENOVATE_IMAGE}" --strict
          exit 0
        fi

        success="true"
        for c in ${INPUTS_CONFIG}; do
          if ! docker run -i --rm -v "$(realpath .):/repo" -w /repo --entrypoint renovate-config-validator "${RENOVATE_IMAGE}" --strict "$c"; then
            echo "::error file=$c,title=Validation failed::Config file did not pass validation"
            success="false"
          fi
        done

        [[ "$success" = "true" ]]
