server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://alloy:3005/loki/api/v1/push

scrape_configs:
  - job_name: logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: myApp
        __path__: /var/log/myCustomLog.txt
        