name: bench-test

on:
  pull_request:
    branches: 
      - main

jobs:
  bench-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/grafana/grafana-bench:latest
      options: --user root
      env:
        GRAFANA_ADDRESS: ${{ secrets.GRAFANA_ADDRESS }}
        GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
        GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
        SCREENSHOT_PATH: screenshots
        USE_COMPILED_TESTS: true
        K6_BROWSER_ENABLED: true
        TEST_PATH: bench
    steps:
      - uses: actions/checkout@v4
      - name: run bench tests
        run: |
          grafana-bench smoke $GRAFANA_ADDRESS $GRAFANA_USER $GRAFANA_PASSWORD all
      - name: Archive screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots
