name: "Publish Playwright report"
description: "Publish a Playwright report to GCS"

inputs:
  grafana-version:
    required: true
    description: "The Grafana version used in the test session that generated the report."
  path:
    default: "playwright-report/"
    required: false
    description: "Path to the folder to publish. Defaults to 'playwright-report/'"

runs:
  using: "composite"
  steps:
    - id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@9f37f656e063f0ad0b0bfc38d49894b57d363936 # v1.2.1
      with:
        common_secrets: |
          GCP_UPLOAD_ARTIFACTS_KEY=grafana/artifacts-uploader-service-account:'credentials.json'
        export_env: false

    - name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093" # v3.0.0
      with:
        credentials_json: "${{ fromJSON(steps.get-secrets.outputs.secrets).GCP_UPLOAD_ARTIFACTS_KEY }}"

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@e427ad8a34f8676edf47cf7d7925499adf3eb74f" # v2.2.1

    - name: Publish report to Cloud Storage
      shell: bash
      run: |
        echo "Publish release to Google Cloud Storage:"
        path=${PUBLISH_REPORT_PATH}
        last_char=${path: -1}
        [[ $last_char != "/" ]] && path="$path/";
        gsutil cp -r "$path". gs://releng-pipeline-artifacts-dev/${EVENT_REPOSITORY_NAME}/${EVENT_NUMBER}/Grafana-v${GRAFANA_VERSION}
      env:
        EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}
        EVENT_NUMBER: ${{ github.event.number }}
        GRAFANA_VERSION: ${{ inputs.grafana-version }}
        PUBLISH_REPORT_PATH: ${{ inputs.path }}

    - name: Write report link to summary
      shell: bash
      run: echo "<a href=\"https://storage.googleapis.com/releng-pipeline-artifacts-dev/$EVENT_REPOSITORY_NAME/$EVENT_NUMBER/Grafana-v$GRAFANA_VERSION/index.html\">Browse the Playwright report for Grafana-v$GRAFANA_VERSION</a>" >> $GITHUB_STEP_SUMMARY
      env:
        EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}
        EVENT_NUMBER: ${{ github.event.number }}
        GRAFANA_VERSION: ${{ inputs.grafana-version }}
