services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v3.5.0}
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp

  loki:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.5.7}
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.10.0}
    ports:
      - 12345:12345 # Alloy HTTP server
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy