apiVersion: 1

datasources:
  - name: "Loki"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: "loki"
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'fake'

  - name: "Loki app"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: "lokiApp"
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'loki_app'
  
  - name: "Loki audit"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: "lokiAudit"
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'loki_audit'
      
  - name: "Loki test app"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: "lokiTestApp"
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'test_loki_app'

  - name: "Loki test audit"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: "lokiTestAudit"
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'test_loki_audit'

