title: Condition Split Query Combination Test Rule
id: 26654045-413c-4db1-be5f-36f34733a865
status: test
description: Tests that when a condition splits a query into multiple queries, they are combined correctly.
author: kleimkuhler
date: 2025-11-06
logsource:
  category: integration-test
detection:
  selection1:
    username: user1
  selection2:
    username: user2
  condition:
    - selection1
    - selection2
falsepositives:
  - This is a test rule, there are no false positives.
level: informational
